[package]
name = "derivatives"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0"
quote = "1.0"
enum-iterator = "1.2"

[lib]
proc-macro = true